### ISSUE TITLE
Bold weight

### ISSUE THREAD

**Issue by bateni** [khaledhosny/noname-fixed#1]
Thanks for taking on this work.  I am a fan of `ALM Fixed` and have used it in `TeXworks` for writing all sorts of Farsi/Arabic texts.  However, without a bold face version, some of the syntax highlighting is suboptimal.

How much work would it be to add a bold weight to this font?  Are you thinking about it, by any chance?

**Comment by khaledhosny** [comment]
ALM Fixed does not include a bold and I’m not sure if the font was designed using MetaFont or by drawing Bézier curves directly. If it is the former then it shouldn’t be too hard to have a bold version if the MetaFont sources are available, otherwise it is going to be a bit of effort.
